<?php

/**
 * This is the model base class for the table "{{user_has_error}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserHasError".
 *
 * Columns in table "{{user_has_error}}" available as properties of the model,
 * followed by relations of table "{{user_has_error}}" available as properties of the model.
 *
 * @property integer $user_has_error_id
 * @property integer $user_id
 * @property integer $error_id
 *
 * @property Error $error
 * @property User $user
 */
abstract class BaseUserHasError extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user_has_error}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserHasError|UserHasErrors', $n);
	}

	public static function representingColumn() {
		return 'user_has_error_id';
	}

	public function rules() {
		return array(
			array('user_id, error_id', 'required'),
			array('user_id, error_id', 'numerical', 'integerOnly'=>true),
			array('user_has_error_id, user_id, error_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'error' => array(self::BELONGS_TO, 'Error', 'error_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_has_error_id' => Yii::t('app', 'User Has Error'),
			'user_id' => null,
			'error_id' => null,
			'error' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_has_error_id', $this->user_has_error_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('error_id', $this->error_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}