<?php

/**
 * This is the model base class for the table "{{user}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "{{user}}" available as properties of the model,
 * followed by relations of table "{{user}}" available as properties of the model.
 *
 * @property integer $user_id
 * @property string $user_hash_id
 *
 * @property UserHasError[] $userHasErrors
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'user_hash_id';
	}

	public function rules() {
		return array(
			array('user_hash_id', 'required'),
			array('user_hash_id', 'length', 'max'=>45),
			array('user_id, user_hash_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'userHasErrors' => array(self::HAS_MANY, 'UserHasError', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'user_hash_id' => Yii::t('app', 'User Hash'),
			'userHasErrors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('user_hash_id', $this->user_hash_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}